name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.18', '1.19']
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            prepare: |
              sudo apt-get update
              sudo apt-get install libudev-dev
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        if: ${{ matrix.prepare }}
        run: ${{ matrix.prepare }}
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: go test ./...

  test-freebsd:
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.18', '1.19']
        include:
          - go-version: '1.18'
            go-pkg: go118
          - go-version: '1.19'
            go-pkg: go119
    steps:
      - uses: actions/checkout@v3
      - uses: vmactions/freebsd-vm@v0
        with:
          copyback: false
          release: '13.1'
          prepare: |
            pkg install -y ${{ matrix.go-pkg }} libiconv
          run: |
            setenv CGO_LDFLAGS -L/usr/local/lib
            ${{ matrix.go-pkg }} test ./...
